server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/users {
        proxy_pass http://user-service:3001;
    }

    location /api/orders {
        proxy_pass http://order-service:3002;
    }

    location /api/restaurants {
        proxy_pass http://restaurant-service:3003;
    }

    location /api/payments {
        proxy_pass http://payment-service:3004;
    }

    location /api/notifications {
        proxy_pass http://notification-service:3005;
    }
}
