services:

  api-gateway:
    image: nginx:alpine
    container_name: quickbite-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - user-service
      - order-service
      - restaurant-service
      - payment-service
      - notification-service
    networks:
      - quickbite-network
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: quickbite-users
    ports:
      - "3001:3001"
    networks:
      - quickbite-network
    restart: unless-stopped

  order-service:
    build: ./order-service
    container_name: quickbite-orders
    ports:
      - "3002:3002"
    networks:
      - quickbite-network
    restart: unless-stopped

  restaurant-service:
    build: ./restaurant-service
    container_name: quickbite-restaurants
    ports:
      - "3003:3003"
    networks:
      - quickbite-network
    restart: unless-stopped

  payment-service:
    build: ./payment-service
    container_name: quickbite-payments
    ports:
      - "3004:3004"
    networks:
      - quickbite-network
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    container_name: quickbite-notifications
    ports:
      - "3005:3005"
    networks:
      - quickbite-network
    restart: unless-stopped

networks:
  quickbite-network:
    driver: bridge
